// <auto-generated />
using System;
using GymTracker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymTracker.Infrastructure.Migrations
{
    [DbContext(typeof(GymTrackerDbContext))]
    [Migration("20260820231447_SeedExerciseCatalog")]
    partial class SeedExerciseCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymTracker.Domain.Entities.CompletedTrainingCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoutineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeeksCompleted")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CompletedTrainingCycles");
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.ExerciseCatalogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultLaterality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExerciseCatalogEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press de Banca"
                        },
                        new
                        {
                            Id = 2,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press de Banca Inclinado"
                        },
                        new
                        {
                            Id = 3,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press de Banca Declinado"
                        },
                        new
                        {
                            Id = 4,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press con Mancuernas"
                        },
                        new
                        {
                            Id = 5,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press Inclinado con Mancuernas"
                        },
                        new
                        {
                            Id = 6,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press en Máquina"
                        },
                        new
                        {
                            Id = 7,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press Hammer Strength"
                        },
                        new
                        {
                            Id = 8,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Chest Press en Máquina"
                        },
                        new
                        {
                            Id = 9,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Aperturas con Mancuernas"
                        },
                        new
                        {
                            Id = 10,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Aperturas en Máquina"
                        },
                        new
                        {
                            Id = 11,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Aperturas en Poleas"
                        },
                        new
                        {
                            Id = 12,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Peck Deck"
                        },
                        new
                        {
                            Id = 13,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press Militar con Barra"
                        },
                        new
                        {
                            Id = 14,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press Militar con Mancuernas"
                        },
                        new
                        {
                            Id = 15,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press Militar en Máquina"
                        },
                        new
                        {
                            Id = 16,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Arnold Press"
                        },
                        new
                        {
                            Id = 17,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Push Press"
                        },
                        new
                        {
                            Id = 18,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Elevaciones Laterales"
                        },
                        new
                        {
                            Id = 19,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Elevaciones Laterales en Máquina"
                        },
                        new
                        {
                            Id = 20,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Elevaciones Frontales"
                        },
                        new
                        {
                            Id = 21,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Pájaros (Deltoide Posterior)"
                        },
                        new
                        {
                            Id = 22,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Reverse Peck Deck"
                        },
                        new
                        {
                            Id = 23,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Fondos en Paralelas"
                        },
                        new
                        {
                            Id = 24,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Fondos en Máquina Asistida"
                        },
                        new
                        {
                            Id = 25,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Fondos en Banco"
                        },
                        new
                        {
                            Id = 26,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Flexiones"
                        },
                        new
                        {
                            Id = 27,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Flexiones Diamante"
                        },
                        new
                        {
                            Id = 28,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Flexiones Declive"
                        },
                        new
                        {
                            Id = 29,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Extensión de Tríceps en Polea"
                        },
                        new
                        {
                            Id = 30,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Extensión de Tríceps con Cuerda"
                        },
                        new
                        {
                            Id = 31,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Extensión de Tríceps en Máquina"
                        },
                        new
                        {
                            Id = 32,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Extensión Overhead con Mancuerna"
                        },
                        new
                        {
                            Id = 33,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Tríceps Francés"
                        },
                        new
                        {
                            Id = 34,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press Cerrado"
                        },
                        new
                        {
                            Id = 35,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Dominadas Pronadas"
                        },
                        new
                        {
                            Id = 36,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Dominadas Supinas (Chin Up)"
                        },
                        new
                        {
                            Id = 37,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Dominadas Neutras"
                        },
                        new
                        {
                            Id = 38,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Dominadas en Máquina Asistida"
                        },
                        new
                        {
                            Id = 39,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Jalón al Pecho"
                        },
                        new
                        {
                            Id = 40,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Jalón Agarre Cerrado"
                        },
                        new
                        {
                            Id = 41,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Jalón Unilateral"
                        },
                        new
                        {
                            Id = 42,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Remo con Barra"
                        },
                        new
                        {
                            Id = 43,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Remo Pendlay"
                        },
                        new
                        {
                            Id = 44,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Remo con Mancuerna"
                        },
                        new
                        {
                            Id = 45,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Remo en Polea Baja"
                        },
                        new
                        {
                            Id = 46,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Remo en Máquina"
                        },
                        new
                        {
                            Id = 47,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Remo Hammer Strength"
                        },
                        new
                        {
                            Id = 48,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Remo T-Bar"
                        },
                        new
                        {
                            Id = 49,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Remo Alto en Polea"
                        },
                        new
                        {
                            Id = 50,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Pullover en Máquina"
                        },
                        new
                        {
                            Id = 51,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Pullover en Polea"
                        },
                        new
                        {
                            Id = 52,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Face Pull"
                        },
                        new
                        {
                            Id = 53,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl de Bíceps con Barra"
                        },
                        new
                        {
                            Id = 54,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl de Bíceps con Mancuernas"
                        },
                        new
                        {
                            Id = 55,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl Martillo"
                        },
                        new
                        {
                            Id = 56,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl en Máquina"
                        },
                        new
                        {
                            Id = 57,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl Predicador"
                        },
                        new
                        {
                            Id = 58,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl Scott"
                        },
                        new
                        {
                            Id = 59,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl en Polea"
                        },
                        new
                        {
                            Id = 60,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Sentadilla Trasera"
                        },
                        new
                        {
                            Id = 61,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Sentadilla Frontal"
                        },
                        new
                        {
                            Id = 62,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Sentadilla Goblet"
                        },
                        new
                        {
                            Id = 63,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Sentadilla Hack"
                        },
                        new
                        {
                            Id = 64,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Sentadilla Hack Inversa"
                        },
                        new
                        {
                            Id = 65,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Sentadilla en Máquina"
                        },
                        new
                        {
                            Id = 66,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Sentadilla Smith"
                        },
                        new
                        {
                            Id = 67,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Prensa de Piernas 45°"
                        },
                        new
                        {
                            Id = 68,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Prensa de Piernas Horizontal"
                        },
                        new
                        {
                            Id = 69,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Prensa de Piernas Unilateral"
                        },
                        new
                        {
                            Id = 70,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Peso Muerto Convencional"
                        },
                        new
                        {
                            Id = 71,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Peso Muerto Sumo"
                        },
                        new
                        {
                            Id = 72,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Peso Muerto Rumano"
                        },
                        new
                        {
                            Id = 73,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Peso Muerto en Máquina"
                        },
                        new
                        {
                            Id = 74,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Hip Thrust con Barra"
                        },
                        new
                        {
                            Id = 75,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Hip Thrust en Máquina"
                        },
                        new
                        {
                            Id = 76,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Zancadas Caminando"
                        },
                        new
                        {
                            Id = 77,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Zancadas Estáticas"
                        },
                        new
                        {
                            Id = 78,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Zancadas Reversas"
                        },
                        new
                        {
                            Id = 79,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Zancadas en Smith"
                        },
                        new
                        {
                            Id = 80,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Extensiones de Cuádriceps"
                        },
                        new
                        {
                            Id = 81,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl Femoral Acostado"
                        },
                        new
                        {
                            Id = 82,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl Femoral Sentado"
                        },
                        new
                        {
                            Id = 83,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl Femoral de Pie"
                        },
                        new
                        {
                            Id = 84,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Aductores en Máquina"
                        },
                        new
                        {
                            Id = 85,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Abductores en Máquina"
                        },
                        new
                        {
                            Id = 86,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Elevación de Gemelos de Pie"
                        },
                        new
                        {
                            Id = 87,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Elevación de Gemelos Sentado"
                        },
                        new
                        {
                            Id = 88,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Gemelos en Prensa"
                        },
                        new
                        {
                            Id = 89,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Crunch Abdominal"
                        },
                        new
                        {
                            Id = 90,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Crunch en Máquina"
                        },
                        new
                        {
                            Id = 91,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Crunch en Polea"
                        },
                        new
                        {
                            Id = 92,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Crunch Declinado"
                        },
                        new
                        {
                            Id = 93,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Plancha Abdominal"
                        },
                        new
                        {
                            Id = 94,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Plancha Lateral"
                        },
                        new
                        {
                            Id = 95,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Plancha con Peso"
                        },
                        new
                        {
                            Id = 96,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Elevaciones de Piernas"
                        },
                        new
                        {
                            Id = 97,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Elevaciones de Piernas Colgado"
                        },
                        new
                        {
                            Id = 98,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Ab Wheel"
                        },
                        new
                        {
                            Id = 99,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Saltar Cuerda"
                        },
                        new
                        {
                            Id = 100,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Burpees"
                        },
                        new
                        {
                            Id = 101,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Jump Squats"
                        },
                        new
                        {
                            Id = 102,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Caminadora"
                        },
                        new
                        {
                            Id = 103,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Bicicleta Estática"
                        },
                        new
                        {
                            Id = 104,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Bicicleta Reclinada"
                        },
                        new
                        {
                            Id = 105,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Elíptica"
                        },
                        new
                        {
                            Id = 106,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Escaladora"
                        },
                        new
                        {
                            Id = 107,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Remo Ergómetro"
                        },
                        new
                        {
                            Id = 108,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Assault Bike"
                        },
                        new
                        {
                            Id = 109,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Wall Sit"
                        },
                        new
                        {
                            Id = 110,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Dead Hang"
                        },
                        new
                        {
                            Id = 111,
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Farmer Walk"
                        });
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.ExerciseNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("NoteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExerciseName")
                        .IsUnique();

                    b.ToTable("ExerciseNotes");
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.Routine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Routines");
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.SessionExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Laterality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("SessionExercise");
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.TrainingCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentWeek")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalWeeks")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TrainingCycles", t =>
                        {
                            t.HasCheckConstraint("CK_TrainingCycles_CurrentWeek_Range", "\"CurrentWeek\" >= 1 AND \"CurrentWeek\" <= \"TotalWeeks\"");
                        });
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.UserExercisePreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Laterality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExerciseName")
                        .IsUnique();

                    b.ToTable("UserExercisePreferences");
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimerPrepSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TimerRestSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TimerSets")
                        .HasColumnType("integer");

                    b.Property<int>("TimerWorkSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RoutineId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoutineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("WorkoutDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.HasIndex("UserId", "WorkoutDate");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Laterality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PrStatus")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercise");
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.ToTable("WorkoutSession");
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.WorkoutSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.Property<Guid>("WorkoutExerciseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("WorkoutSet", t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutSets_Reps_NonNegative", "\"Reps\" >= 0");

                            t.HasCheckConstraint("CK_WorkoutSets_SetNumber_Positive", "\"SetNumber\" > 0");

                            t.HasCheckConstraint("CK_WorkoutSets_Weight_NonNegative", "\"Weight\" >= 0");
                        });
                });

            modelBuilder.Entity("GymTracker.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.CompletedTrainingCycle", b =>
                {
                    b.HasOne("GymTracker.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.ExerciseNote", b =>
                {
                    b.HasOne("GymTracker.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.Routine", b =>
                {
                    b.HasOne("GymTracker.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.SessionExercise", b =>
                {
                    b.HasOne("GymTracker.Domain.Entities.WorkoutSession", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.TrainingCycle", b =>
                {
                    b.HasOne("GymTracker.Domain.Entities.Routine", null)
                        .WithMany()
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymTracker.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.UserExercisePreference", b =>
                {
                    b.HasOne("GymTracker.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("GymTracker.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.Workout", b =>
                {
                    b.HasOne("GymTracker.Domain.Entities.Routine", null)
                        .WithMany()
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GymTracker.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.WorkoutExercise", b =>
                {
                    b.HasOne("GymTracker.Domain.Entities.Workout", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.WorkoutSession", b =>
                {
                    b.HasOne("GymTracker.Domain.Entities.Routine", null)
                        .WithMany("Sessions")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.WorkoutSet", b =>
                {
                    b.HasOne("GymTracker.Domain.Entities.WorkoutExercise", null)
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GymTracker.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GymTracker.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTracker.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GymTracker.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.Routine", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.Workout", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.WorkoutExercise", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("GymTracker.Domain.Entities.WorkoutSession", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
