using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace GymTracker.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class SeedExerciseCatalog : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // La tabla está vacía: se cambia el tipo con cast explícito (uuid -> integer)
            // y se convierte la columna en identity (GENERATED BY DEFAULT AS IDENTITY).
            migrationBuilder.Sql(
                "ALTER TABLE \"ExerciseCatalogEntries\" ALTER COLUMN \"Id\" TYPE integer USING \"Id\"::text::integer;");
            migrationBuilder.Sql(
                "ALTER TABLE \"ExerciseCatalogEntries\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");

            migrationBuilder.InsertData(
                table: "ExerciseCatalogEntries",
                columns: new[] { "Id", "DefaultLaterality", "ExerciseType", "Name" },
                values: new object[,]
                {
                    { 1, "Bilateral", "Standard", "Press de Banca" },
                    { 2, "Bilateral", "Standard", "Press de Banca Inclinado" },
                    { 3, "Bilateral", "Standard", "Press de Banca Declinado" },
                    { 4, "Bilateral", "Standard", "Press con Mancuernas" },
                    { 5, "Bilateral", "Standard", "Press Inclinado con Mancuernas" },
                    { 6, "Bilateral", "Standard", "Press en Máquina" },
                    { 7, "Bilateral", "Standard", "Press Hammer Strength" },
                    { 8, "Bilateral", "Standard", "Chest Press en Máquina" },
                    { 9, "Bilateral", "Standard", "Aperturas con Mancuernas" },
                    { 10, "Bilateral", "Standard", "Aperturas en Máquina" },
                    { 11, "Bilateral", "Standard", "Aperturas en Poleas" },
                    { 12, "Bilateral", "Standard", "Peck Deck" },
                    { 13, "Bilateral", "Standard", "Press Militar con Barra" },
                    { 14, "Bilateral", "Standard", "Press Militar con Mancuernas" },
                    { 15, "Bilateral", "Standard", "Press Militar en Máquina" },
                    { 16, "Bilateral", "Standard", "Arnold Press" },
                    { 17, "Bilateral", "Standard", "Push Press" },
                    { 18, "Bilateral", "Standard", "Elevaciones Laterales" },
                    { 19, "Bilateral", "Standard", "Elevaciones Laterales en Máquina" },
                    { 20, "Bilateral", "Standard", "Elevaciones Frontales" },
                    { 21, "Bilateral", "Standard", "Pájaros (Deltoide Posterior)" },
                    { 22, "Bilateral", "Standard", "Reverse Peck Deck" },
                    { 23, "Bilateral", "Bodyweight", "Fondos en Paralelas" },
                    { 24, "Bilateral", "Standard", "Fondos en Máquina Asistida" },
                    { 25, "Bilateral", "Bodyweight", "Fondos en Banco" },
                    { 26, "Bilateral", "Bodyweight", "Flexiones" },
                    { 27, "Bilateral", "Bodyweight", "Flexiones Diamante" },
                    { 28, "Bilateral", "Bodyweight", "Flexiones Declive" },
                    { 29, "Bilateral", "Standard", "Extensión de Tríceps en Polea" },
                    { 30, "Bilateral", "Standard", "Extensión de Tríceps con Cuerda" },
                    { 31, "Bilateral", "Standard", "Extensión de Tríceps en Máquina" },
                    { 32, "Bilateral", "Standard", "Extensión Overhead con Mancuerna" },
                    { 33, "Bilateral", "Standard", "Tríceps Francés" },
                    { 34, "Bilateral", "Standard", "Press Cerrado" },
                    { 35, "Bilateral", "Bodyweight", "Dominadas Pronadas" },
                    { 36, "Bilateral", "Bodyweight", "Dominadas Supinas (Chin Up)" },
                    { 37, "Bilateral", "Bodyweight", "Dominadas Neutras" },
                    { 38, "Bilateral", "Standard", "Dominadas en Máquina Asistida" },
                    { 39, "Bilateral", "Standard", "Jalón al Pecho" },
                    { 40, "Bilateral", "Standard", "Jalón Agarre Cerrado" },
                    { 41, "Bilateral", "Standard", "Jalón Unilateral" },
                    { 42, "Bilateral", "Standard", "Remo con Barra" },
                    { 43, "Bilateral", "Standard", "Remo Pendlay" },
                    { 44, "Bilateral", "Standard", "Remo con Mancuerna" },
                    { 45, "Bilateral", "Standard", "Remo en Polea Baja" },
                    { 46, "Bilateral", "Standard", "Remo en Máquina" },
                    { 47, "Bilateral", "Standard", "Remo Hammer Strength" },
                    { 48, "Bilateral", "Standard", "Remo T-Bar" },
                    { 49, "Bilateral", "Standard", "Remo Alto en Polea" },
                    { 50, "Bilateral", "Standard", "Pullover en Máquina" },
                    { 51, "Bilateral", "Standard", "Pullover en Polea" },
                    { 52, "Bilateral", "Standard", "Face Pull" },
                    { 53, "Bilateral", "Standard", "Curl de Bíceps con Barra" },
                    { 54, "Bilateral", "Standard", "Curl de Bíceps con Mancuernas" },
                    { 55, "Bilateral", "Standard", "Curl Martillo" },
                    { 56, "Bilateral", "Standard", "Curl en Máquina" },
                    { 57, "Bilateral", "Standard", "Curl Predicador" },
                    { 58, "Bilateral", "Standard", "Curl Scott" },
                    { 59, "Bilateral", "Standard", "Curl en Polea" },
                    { 60, "Bilateral", "Standard", "Sentadilla Trasera" },
                    { 61, "Bilateral", "Standard", "Sentadilla Frontal" },
                    { 62, "Bilateral", "Standard", "Sentadilla Goblet" },
                    { 63, "Bilateral", "Standard", "Sentadilla Hack" },
                    { 64, "Bilateral", "Standard", "Sentadilla Hack Inversa" },
                    { 65, "Bilateral", "Standard", "Sentadilla en Máquina" },
                    { 66, "Bilateral", "Standard", "Sentadilla Smith" },
                    { 67, "Bilateral", "Standard", "Prensa de Piernas 45°" },
                    { 68, "Bilateral", "Standard", "Prensa de Piernas Horizontal" },
                    { 69, "Bilateral", "Standard", "Prensa de Piernas Unilateral" },
                    { 70, "Bilateral", "Standard", "Peso Muerto Convencional" },
                    { 71, "Bilateral", "Standard", "Peso Muerto Sumo" },
                    { 72, "Bilateral", "Standard", "Peso Muerto Rumano" },
                    { 73, "Bilateral", "Standard", "Peso Muerto en Máquina" },
                    { 74, "Bilateral", "Standard", "Hip Thrust con Barra" },
                    { 75, "Bilateral", "Standard", "Hip Thrust en Máquina" },
                    { 76, "Bilateral", "Standard", "Zancadas Caminando" },
                    { 77, "Bilateral", "Standard", "Zancadas Estáticas" },
                    { 78, "Bilateral", "Standard", "Zancadas Reversas" },
                    { 79, "Bilateral", "Standard", "Zancadas en Smith" },
                    { 80, "Bilateral", "Standard", "Extensiones de Cuádriceps" },
                    { 81, "Bilateral", "Standard", "Curl Femoral Acostado" },
                    { 82, "Bilateral", "Standard", "Curl Femoral Sentado" },
                    { 83, "Bilateral", "Standard", "Curl Femoral de Pie" },
                    { 84, "Bilateral", "Standard", "Aductores en Máquina" },
                    { 85, "Bilateral", "Standard", "Abductores en Máquina" },
                    { 86, "Bilateral", "Standard", "Elevación de Gemelos de Pie" },
                    { 87, "Bilateral", "Standard", "Elevación de Gemelos Sentado" },
                    { 88, "Bilateral", "Standard", "Gemelos en Prensa" },
                    { 89, "Bilateral", "Bodyweight", "Crunch Abdominal" },
                    { 90, "Bilateral", "Standard", "Crunch en Máquina" },
                    { 91, "Bilateral", "Standard", "Crunch en Polea" },
                    { 92, "Bilateral", "Bodyweight", "Crunch Declinado" },
                    { 93, "Bilateral", "Time", "Plancha Abdominal" },
                    { 94, "Bilateral", "Time", "Plancha Lateral" },
                    { 95, "Bilateral", "Time", "Plancha con Peso" },
                    { 96, "Bilateral", "Bodyweight", "Elevaciones de Piernas" },
                    { 97, "Bilateral", "Bodyweight", "Elevaciones de Piernas Colgado" },
                    { 98, "Bilateral", "Bodyweight", "Ab Wheel" },
                    { 99, "Bilateral", "Time", "Saltar Cuerda" },
                    { 100, "Bilateral", "Bodyweight", "Burpees" },
                    { 101, "Bilateral", "Bodyweight", "Jump Squats" },
                    { 102, "Bilateral", "Time", "Caminadora" },
                    { 103, "Bilateral", "Time", "Bicicleta Estática" },
                    { 104, "Bilateral", "Time", "Bicicleta Reclinada" },
                    { 105, "Bilateral", "Time", "Elíptica" },
                    { 106, "Bilateral", "Time", "Escaladora" },
                    { 107, "Bilateral", "Time", "Remo Ergómetro" },
                    { 108, "Bilateral", "Time", "Assault Bike" },
                    { 109, "Bilateral", "Time", "Wall Sit" },
                    { 110, "Bilateral", "Time", "Dead Hang" },
                    { 111, "Bilateral", "Time", "Farmer Walk" }
                });

            // El seed inserta IDs explícitos; la secuencia del identity no avanza sola.
            // Se reajusta al máximo Id sembrado para que el próximo INSERT automático no colisione.
            migrationBuilder.Sql(
                "SELECT setval(pg_get_serial_sequence('\"ExerciseCatalogEntries\"', 'Id'), "
                + "(SELECT COALESCE(MAX(\"Id\"), 1) FROM \"ExerciseCatalogEntries\"));");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 1);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 2);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 3);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 4);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 5);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 6);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 7);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 8);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 9);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 10);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 11);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 12);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 13);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 14);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 15);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 16);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 17);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 18);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 19);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 20);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 21);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 22);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 23);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 24);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 25);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 26);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 27);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 28);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 29);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 30);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 31);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 32);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 33);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 34);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 35);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 36);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 37);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 38);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 39);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 40);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 41);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 42);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 43);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 44);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 45);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 46);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 47);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 48);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 49);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 50);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 51);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 52);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 53);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 54);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 55);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 56);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 57);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 58);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 59);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 60);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 61);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 62);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 63);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 64);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 65);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 66);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 67);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 68);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 69);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 70);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 71);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 72);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 73);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 74);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 75);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 76);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 77);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 78);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 79);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 80);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 81);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 82);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 83);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 84);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 85);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 86);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 87);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 88);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 89);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 90);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 91);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 92);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 93);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 94);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 95);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 96);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 97);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 98);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 99);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 100);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 101);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 102);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 103);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 104);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 105);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 106);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 107);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 108);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 109);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 110);

            migrationBuilder.DeleteData(
                table: "ExerciseCatalogEntries",
                keyColumn: "Id",
                keyValue: 111);

            migrationBuilder.Sql(
                "ALTER TABLE \"ExerciseCatalogEntries\" ALTER COLUMN \"Id\" DROP IDENTITY;");
            migrationBuilder.Sql(
                "ALTER TABLE \"ExerciseCatalogEntries\" ALTER COLUMN \"Id\" TYPE uuid USING \"Id\"::text::uuid;");
        }
    }
}
